config/routes.rb
Mohhaiti::Application.routes.draw do

  match "/donate-today" => redirect("https://secure3.convio.net/mohh/site/Donation2?df_id=1600&1600.donation=form1"), :as => :donate_today 

  get "/intern_thank_you" => "page#intern_thank_you"
  
  resources :interns do

    member do
      get "archive"
      put "archive"
      post "archive"
    end
    match "/interns/:id/archive" => "interns#archive"
    
  end  
  
  get "/archived_interns" => "page#archived_interns"

  resources :subscriptions

  match "/blog/feed.xml" => "posts#rss", :action => 'rss'
  
  match "/bluetoblock" => "projects#bluetoblock"
  put "/projects/5" => "projects#update", :id => 5
  match "/projects/5" => "projects#bluetoblock"

  get "projects/transition_home" => "projects#project15extra"
  get "projects/project15extra" =>  "projects#project15extra"
  resources :news

  resources :videos

  resources :events

  resources :categories

  get "category/index"

  get "category/show"

  get "category/update"

  resources :posts

  resources :experiences

  resources :partners

  root :to => 'home#index'

  resources :contents

  resources :tags

  resources :updates

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  match "/users/password_reset" => "users#password_reset"
  match "/users/password_reset/:token" => "users#password_reset_edit"
  resources :users

  resources :projects

  resources :communities
  
  resources :sessions
  
  resources :blog, :controller => "posts"
  
  resources :villages, :controller => "communities"
  
  get "home/index"
  
  

  match "/about_moh" => redirect("/about_us")
  match "/about_moh/history" => redirect("/")
  match "/about_moh/in_the_news/" => redirect("/press")  
  match "/about_moh/staff/:any" => redirect("/meet_our_staff")
  match "/about_moh/staff/" => redirect("/meet_our_staff")
  match "/about_moh/vision_and_resolution/" => redirect("/vision_mission_resolution")
  match "/about_moh/our_progress_in_haiti/" => redirect("/what-we-do")
  match "/about_moh/haiti_info/" => redirect("/about_haiti")
  match "/about_moh/contact_us/" => redirect("/contact_us")
  match "/about_moh/privacy_policy/" => redirect("/privacy")
  match "/about_moh/videos/" => redirect("/videos")
  match "/about_moh/what_we_believe" => redirect("/")
  
  match "/blog" => redirect("/posts")
  
  match "/contact-us" => redirect("/contact_us")
  
  match "/get_involved/" => redirect("/take-action")
  match "/get_involved/donations" => redirect("/take-action")
  match "/get_involved/partners_of_hope" => redirect("/partner_of_hope")
  match "/get_involved/child_sponsorships/faq/" => redirect("/sponsor_faq")
  match "/get_involved/child_sponsorships/cs_store/" => redirect("/gift_store")
  match "/get_involved/child_sponsorships/" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/orphan_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/student_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/church_partnerships" => redirect("/church_partner")
  match "/get_involved/church_partnerships/vision_trip_dates" => redirect("/vision_trip")
  match "/get_involved/employment_opportunities/" => redirect("/about_us")
  match "/get_involved/events/" => redirect("/events")
  match "/get_involved/internships/" => redirect("/internships")
  match "/get_involved/mission_trips/" => redirect("/mission_trips")
  match "/get_involved/mission_trips/faq1" => redirect("/trip_faqs")
  match "/get_involved/mission_trips/preparing_for_your_trip/" => redirect("/preparing_for_mission_trips")
  match "/get_involved/mission_trips/trip_costs" => redirect("/trip_costs")
  match "/get_involved/mission_trips/trip_dates" => redirect("/trip_dates")
  match "/get_involved/prayer_needs/" => redirect("/take-action")
  
  match "/news" => redirect("/press")
  
  get "/sponsorship/say_yes" => "sponsorship#say_yes"
  match "/take-the-plunge" => redirect("/mission_trips")
  
  match "/what_we_do/3cords/" => redirect("/three_cords")
  match "/what_we_do/church_advancement/" => redirect("/church_advancement")
  match "/what_we_do/education1/" => redirect("/education")
  match "/what_we_do/education1/christian_curriculum/" => redirect("/mwen_kapab")
  match "/what_we_do/future_plans/" => redirect("/projects")
  match "/what_we_do/future_plans/:any" => redirect("/projects")
  match "/what_we_do/haiti_one/" => redirect("/haiti_one")
  match "/what_we_do/medical_care/" => redirect("/health_care")
  match "/what_we_do/medical_care/prosthetics_lab" => redirect("/prosthetics")
  match "/what_we_do/medical_care/community_health_program" => redirect("/community_health")
 
  match "/what_we_do/moh_500/" => redirect("/projects/5")
  match "/what_we_do/nutrition/" => redirect("/nutrition")
  match "/what_we_do/orphan_care/" => redirect("/orphan_care")
  match "/what_we_do/" => redirect("/what-we-do")
  
  
  
  
  get "page/newsletter_thank_you"
  match "/newsletter_thank_you" => "page#newsletter_thank_you"
  
  get "page/sitemap"
  match "/sitemap" => "page#sitemap"
  
  get "page/what_we_do"
  match "/what-we-do" => "page#what_we_do"
  
  get "page/about_us"
  match "/about_us" => "page#about_us"
  
  get "page/caprojects"
  match "/caprojects" => "page#caprojects"
  
  get "page/contact_us"
  match "/contact_us" => "page#contact_us"
  
  get "page/videos"
  match "/videos" => "page#videos"
  
  get "page/haiti_one"
  match "/haiti_one" => "page#haiti_one"
  
  get "page/meal_packing"
  match "/meal_packing" => "page#meal_packing"

  get "page/mission_trips"
  match "/mission_trips" => "page#mission_trips"
    
  get "page/about_haiti"
  match "/about_haiti" => "page#about_haiti"
    
  get "page/orphan_care"
  match "/orphan_care" => "page#orphan_care"
  match "/orphan-care" => "page#orphan_care"
  
  get "page/education"
  match "/education" => "page#education"
  
  get "page/health_care"
  match "/health_care" => "page#health_care"
  
  get "page/three_cords"
  match "/three_cords" => "page#three_cords"
    
  get "page/meet_our_staff"
  match "/meet_our_staff" => "page#meet_our_staff"
  
  get "page/orphan_sponsorship"
  match "/orphan_sponsorship" => "page#orphan_sponsorship"
  
  get "page/clinic"
  match "/clinic" => "page#clinic"
  
  get "page/our_story"
  match "/our_story" => "page#our_story"
  
  get "page/community_health"
  match "/community_health" => "page#community_health"
 
  get "page/prosthetics"
  match "/prosthetics" => "page#prosthetics"
     
  get "page/internships"
  match "/internships" => "page#internships"
  
  get "/intern_application" => "interns#new"
  
  get "page/privacy"
  match "/privacy" => "page#privacy"
  
  get "page/financial_info"
  match "/financial_info" => "page#financial_info"
  
  get "page/press"
  match "/press" => "page#press"
  
  get "page/school_of_hope"
  match "/school_of_hope" => "page#school_of_hope"
  
  get "page/mwen_kapab"
  match "/mwen_kapab" => "page#mwen_kapab"
  
  get "page/vision_mission_resolution"
  match "/vision_mission_resolution" => "page#vision_mission_resolution"
  
  get "page/join_our_team"
  match "/join_our_team" => "page#join_our_team"
  
  get "page/partner_of_hope"
  match "/partner_of_hope" => "page#partner_of_hope"
  
  get "page/nutrition"
  match "/nutrition" => "page#nutrition"
  
  get "page/medical_mission_trips"
  match "/medical_mission_trips" => "page#medical_mission_trips"
     
  get "page/mission_trip_experinces"
  match "/mission_trip_experinces" => "page#mission_trip_experiences"
  
  get "page/mission_trip_experiences"
  match "/mission_trip_experiences" => "page#mission_trip_experiences"
  
  get "page/image_submit"
  match "/page/image_submit" => "page#image_submit"
   
  get "page/preparing_for_mission_trips"
  match "/preparing_for_mission_trips" => "page#preparing_for_mission_trips"
     
  get "page/request_info"
  match "/request_info" => "page#request_info"
  
  get "page/request_info_medical"
  match "/request_info_medical" => "page#request_info_medical"
     
  get "page/trip_costs"
  match "/trip_costs" => "page#trip_costs"
     
     
  get "page/trip_faqs"
  match "/trip_faqs" => "page#trip_faqs"
        
  get "page/communities_impacted"
  match "/communities_impacted" => "page#communities_impacted"
        
  get "page/church_partner"
  match "/church_partner" => "page#church_partner"
        
  get "page/vision_trip"
  match "/vision_trip" => "page#vision_trip"
    
  get "page/downloads"
  match "/downloads" => "page#downloads"
  
  get "page/faq"
  match "/faq" => "page#faq"
    
  get "page/make_donation"
  match "/make_donation" => "page#make_donation"
    
  get "page/be_a_partner"
  match "/be_a_partner" => "page#be_a_partner"
 
  get "page/volunteer"
  match "/volunteer" => "page#volunteer"   
    
  get "page/share_photos"
  match "/share_photos" => "page#share_photos"
    
  get "page/event"
  match "/event" => "page#event"
          
  get "page/sponsor_child"
  match "/sponsor_child" => "page#sponsor_child"
          
  get "page/learn_sponsor"
  match "/learn_sponsor" => "page#learn_sponsor"
          
  get "page/sponsor_faq"
  match "/sponsor_faq" => "page#sponsor_faq"
          
  get "page/gift_store"
  match "/gift_store" => "page#gift_store"
          
  get "page/write_my_child"
  match "/write_my_child" => "page#write_my_child"
  
  match "/write-my-child" => "page#write_my_child"
      
  get "page/console"
  match "/console" => "page#console"
  
  get "mymoh/account"
  get "mymoh/status_check"
  get "mymoh/home"
  get "mymoh/giving"
  get "mymoh/giving/edit" => "mymoh#givingedit"
  post "mymoh/giving/edit" => "mymoh#givingedit_post"
  get "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/giving/receipt/:gift_id" => "mymoh#givingreceipt"
  post "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/sponsorships"
  get "mymoh/mytrips"
  get "mymoh/login"
  get "mymoh/following"

app/models/content.rb
class Content < ActiveRecord::Base

  validates_uniqueness_of :url

  def to_param
    url
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  
  layout 'homeLayout'
  
  def index
    if is_admin_user?
      @contents = Content.all
  
      respond_to do |format|
       format.html {render :layout=>"homeLayout"}# index.html.erb
        format.json { render json: @contents }
      end
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    #@content = Content.find(params[:id])
    #@content = Content.find(1)
    #@thisParam = request.fullpath #params[:id]
    if !params[:id].nil?
      @content = Content.find(params[:id])
    else
      if params[:path].nil?
        @content = Content.find_by_url(params[:url])
      else
        @content = Content.find_by_url(params[:path] + '/' + params[:url])
      end
    end
    
    if @content
      @title = @content.title
      @meta = @content.description
      respond_to do |format|
        format.html {render :layout=>"homeLayout" }# index.html.erb
        format.json { render json: @content }
      end
    else
     raise ActionController::RoutingError.new('Not Found')
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    if is_admin_user?
      @content = Content.new
  
      respond_to do |format|
       format.html {render :layout=>"homeLayout"}# index.html.erb
        format.json { render json: @content }
      end
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end

  # GET /contents/1/edit
  def edit
    if is_admin_user?
      #@content = Content.find(params[:id])
      @content = Content.find_by_id(params[:id])
      respond_to do |format|
        format.html {render :layout=>"homeLayout"}# index.html.erb
      end
      #@content = Content.find_by_url(params[:id])
      #@content = Content.where("id = 20")
      #@content = Content.find_by_url("no-path")
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end

  # POST /contents
  # POST /contents.json
  def create
    if is_admin_user?
      @content = Content.new(params[:content])
  
      respond_to do |format|
        if @content.save
          format.html { redirect_to '/' + params[:content][:url], notice: 'Content was successfully created.' }
          format.json { render json: @content, status: :created, location: @content }
        else
          format.html { render action: "new" }
          format.json { render json: @content.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    if is_admin_user?
      @content = Content.find_by_id(params[:id])
      #@content = Content.where("id = ?",params[:id])
      #@content = Content.find_by_url("no-path")
  
      respond_to do |format|
        if @content.update_attributes(params[:content])
          format.html { redirect_to '/' + params[:content][:url], notice: "Content successfully updated" }
          format.json { head :ok }
        else
          format.html { render action: "edit" }
          format.json { render json: @content.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    if is_admin_user?
      #@content = Content.find(params[:id])
      @content = Content.find_by_id(params[:id])
      @content.destroy
  
      respond_to do |format|
        format.html { redirect_to contents_url }
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { redirect_to "/" }
      end
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<script type="text/javascript" src="/assets/tinymce/jscripts/tiny_mce/tiny_mce.js" ></script >
<script type="text/javascript" >
tinyMCE.init({
        mode : "textareas",
        width: "100%",
        theme : "advanced",
        plugins : "emotions,spellchecker,advhr,insertdatetime,preview", 
                
        // Theme options - button# indicated the row# only
        theme_advanced_buttons1 : "newdocument,|,bold,italic,underline,|,justifyleft,justifycenter,justifyright,fontselect,fontsizeselect,formatselect",
        theme_advanced_buttons2 : "cut,copy,paste,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,|,code,preview,|,forecolor,backcolor",
        theme_advanced_buttons3 : "insertdate,inserttime,|,spellchecker,advhr,,removeformat,|,sub,sup,|,charmap,emotions",      
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        theme_advanced_resizing : true
});
</script >

<%= form_for(@content, :url=>'/contents/' + @content.id.to_s()) do |f| %>

    <% @navoptions={ "About Us" => "aboutNav", "Child Sponsor" => "childSponsorNav","Church" => "churchNav", "Health Care" => "healthCareNav"} %>
    <% @navoptions.merge!("Mission Trip" => "missionTripNav", "Take Action" => "takeActionNav") %>

  <div class="field">
    <h2><%= f.label :url %></h2>
    <%= f.text_field :url %><br />
    <h2>Hero Image Filename (can be blank)</h2>
    <%= f.text_field :heroimage %><br />
    <h2>Hero Image Text (can be blank)</h2>
    <%= f.text_field :heroimage %><br />
    <h2>Description (meta)</h2>
    <%= f.text_field :description %><br />  
    <h2>Title (meta)</h2>
    <%= f.text_field :title %><br />  
    <h2>Right Menu Navigation</h2>
    <%= select( "content", "navbar", @navoptions) %>
    <h2><%= f.label :content %></h2>
    <%= f.text_area :content %><br />
    <h2><%= f.label :headline %></h2>
    <%= f.text_field :headline %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div id="wrapper">
	<%=render 'layouts/navBar'%>
	<div id="content" style="padding-top: 0px;">
		<h1>Edit content</h1>
		<div id="cms">
			<%= render 'form' %>

			<div class="smallLink"><a href="/<%=@content.url%>">View this Page</a> | <%= link_to 'Back', contents_path %></div>
		</div>
	</div>
</div>

app/views/contents/index.html.erb
<div id="wrapper">
	<%=render 'layouts/navBar'%>
<div id="content" style="padding-top:50px;">
<h1>Edit or Create Content</h1>
<div id="cms">
<h2><%= link_to 'Create New Content', new_content_path %></h2> 
<h2>Edit Existing Content</h2>
<% @contents.each do |content| %>
  <div class="contentList">
    <p><strong>URL:</strong> <%= content.url %></p>
	<p><strong>Headline:</strong> <%= content.headline %></p>
	<p><strong>Page HTML:</strong> <%= truncate(strip_tags(content.content),:length=>100,:separator=>' ').html_safe%></p>
    <p class="smallLink"><a href="/<%=content.url%>">View this Page</a></td>&nbsp;| <a href="/contents/<%=content.id%>/edit">Edit this Page</a> | <a href="/contents/<%=content.id%>" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Delete this Page</a></p>
  </div>
<% end %>
</div>

</div>
</div>

app/views/contents/new.html.erb
<div id="wrapper">
	<%=render 'layouts/navBar'%>
<div id="content" style="padding-top: 50px;">
<h1>Create New Content</h1>
<div id="cms">
<%= render 'form' %>

<div class="smallLink">&laquo; <%= link_to 'Back', contents_path %></div>
</div>
</div>
</div>

app/views/contents/show.html.erb
<!-- content show -->
<%if !@content.nil? && !@content.heroimage.nil? && @content.heroimage != '' %>
	<div id="bgHero" >
		<%if !@content.nil? && !@content.heroimage.nil? && @content.heroimage != '' %>
			<div id="heroCommunitiesImg" style="background: url(/assets/<%=@content.heroimage%>) no-repeat center center; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover;background-size: cover;">
				<!--x-->
			</div>
		<%else%>
			<div id="heroCommunitiesImg">
			<!--x-->
			</div>
		<%end%>
	</div>
<% end %>
<div id="wrapper">
	<%=render 'layouts/navBar'%>
	<%if !@content.nil? && !@content.heroimage.nil? && @content.heroimage != '' %>
		<div id="content" style="padding-top:500px;">
	<% else %>
		<div id="content" style="padding-top:50px;">
	<% end %>
		<% if @content && !@content.heroimage.nil? && @content.heroimage != '' && !@content.herotext.nil? && !(@content.herotext == "") %>
			<div id="heroContent">
				<h1 style="top:-158px;"><span class="greenTransBG"><span style="font-size: 2.5em;"><%=@content.herotext%></span></span></h1>
			</div>
		<% end %>
		<p id="notice"><%= notice %></p>

		<div id="contentLeft560">
			<% if @content %>
				<%=@content.content.html_safe%>
			<% else %>
				<h1>Page Not Found</h1>
			<% end %>
			<% if !@user.nil? && @user.is_admin == 1 %><div class="smallLink"><%= link_to 'Back', contents_path %> | <a href="/contents/<%=@content.id%>/edit">Edit</a></div><% end %>
		</div>


		<div id="contentRight300" style="padding-top: 38px;">
			<% if @content %>
				<%if !@content.navbar.nil? %>
					<%= render ("layouts/" + @content.navbar) %>
				<% else %>
					<%= render "layouts/aboutNav" %>
				<% end%>
			<% end %>
		</div>
		<div class="clearfix">
			<!--x-->
		</div>

	
	</div>
</div>