config/routes.rb
Mohhaiti::Application.routes.draw do

  match "/donate-today" => redirect("https://secure3.convio.net/mohh/site/Donation2?df_id=1600&1600.donation=form1"), :as => :donate_today 

  get "/intern_thank_you" => "page#intern_thank_you"
  
  resources :interns do

    member do
      get "archive"
      put "archive"
      post "archive"
    end
    match "/interns/:id/archive" => "interns#archive"
    
  end  
  
  get "/archived_interns" => "page#archived_interns"

  resources :subscriptions

  match "/blog/feed.xml" => "posts#rss", :action => 'rss'
  
  match "/bluetoblock" => "projects#bluetoblock"
  put "/projects/5" => "projects#update", :id => 5
  match "/projects/5" => "projects#bluetoblock"

  get "projects/transition_home" => "projects#project15extra"
  get "projects/project15extra" =>  "projects#project15extra"
  resources :news

  resources :videos

  resources :events

  resources :categories

  get "category/index"

  get "category/show"

  get "category/update"

  resources :posts

  resources :experiences

  resources :partners

  root :to => 'home#index'

  resources :contents

  resources :tags

  resources :updates

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  match "/users/password_reset" => "users#password_reset"
  match "/users/password_reset/:token" => "users#password_reset_edit"
  resources :users

  resources :projects

  resources :communities
  
  resources :sessions
  
  resources :blog, :controller => "posts"
  
  resources :villages, :controller => "communities"
  
  get "home/index"
  
  

  match "/about_moh" => redirect("/about_us")
  match "/about_moh/history" => redirect("/")
  match "/about_moh/in_the_news/" => redirect("/press")  
  match "/about_moh/staff/:any" => redirect("/meet_our_staff")
  match "/about_moh/staff/" => redirect("/meet_our_staff")
  match "/about_moh/vision_and_resolution/" => redirect("/vision_mission_resolution")
  match "/about_moh/our_progress_in_haiti/" => redirect("/what-we-do")
  match "/about_moh/haiti_info/" => redirect("/about_haiti")
  match "/about_moh/contact_us/" => redirect("/contact_us")
  match "/about_moh/privacy_policy/" => redirect("/privacy")
  match "/about_moh/videos/" => redirect("/videos")
  match "/about_moh/what_we_believe" => redirect("/")
  
  match "/blog" => redirect("/posts")
  
  match "/contact-us" => redirect("/contact_us")
  
  match "/get_involved/" => redirect("/take-action")
  match "/get_involved/donations" => redirect("/take-action")
  match "/get_involved/partners_of_hope" => redirect("/partner_of_hope")
  match "/get_involved/child_sponsorships/faq/" => redirect("/sponsor_faq")
  match "/get_involved/child_sponsorships/cs_store/" => redirect("/gift_store")
  match "/get_involved/child_sponsorships/" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/orphan_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/student_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/church_partnerships" => redirect("/church_partner")
  match "/get_involved/church_partnerships/vision_trip_dates" => redirect("/vision_trip")
  match "/get_involved/employment_opportunities/" => redirect("/about_us")
  match "/get_involved/events/" => redirect("/events")
  match "/get_involved/internships/" => redirect("/internships")
  match "/get_involved/mission_trips/" => redirect("/mission_trips")
  match "/get_involved/mission_trips/faq1" => redirect("/trip_faqs")
  match "/get_involved/mission_trips/preparing_for_your_trip/" => redirect("/preparing_for_mission_trips")
  match "/get_involved/mission_trips/trip_costs" => redirect("/trip_costs")
  match "/get_involved/mission_trips/trip_dates" => redirect("/trip_dates")
  match "/get_involved/prayer_needs/" => redirect("/take-action")
  
  match "/news" => redirect("/press")
  
  get "/sponsorship/say_yes" => "sponsorship#say_yes"
  match "/take-the-plunge" => redirect("/mission_trips")
  
  match "/what_we_do/3cords/" => redirect("/three_cords")
  match "/what_we_do/church_advancement/" => redirect("/church_advancement")
  match "/what_we_do/education1/" => redirect("/education")
  match "/what_we_do/education1/christian_curriculum/" => redirect("/mwen_kapab")
  match "/what_we_do/future_plans/" => redirect("/projects")
  match "/what_we_do/future_plans/:any" => redirect("/projects")
  match "/what_we_do/haiti_one/" => redirect("/haiti_one")
  match "/what_we_do/medical_care/" => redirect("/health_care")
  match "/what_we_do/medical_care/prosthetics_lab" => redirect("/prosthetics")
  match "/what_we_do/medical_care/community_health_program" => redirect("/community_health")
 
  match "/what_we_do/moh_500/" => redirect("/projects/5")
  match "/what_we_do/nutrition/" => redirect("/nutrition")
  match "/what_we_do/orphan_care/" => redirect("/orphan_care")
  match "/what_we_do/" => redirect("/what-we-do")
  
  
  
  
  get "page/newsletter_thank_you"
  match "/newsletter_thank_you" => "page#newsletter_thank_you"
  
  get "page/sitemap"
  match "/sitemap" => "page#sitemap"
  
  get "page/what_we_do"
  match "/what-we-do" => "page#what_we_do"
  
  get "page/about_us"
  match "/about_us" => "page#about_us"
  
  get "page/caprojects"
  match "/caprojects" => "page#caprojects"
  
  get "page/contact_us"
  match "/contact_us" => "page#contact_us"
  
  get "page/videos"
  match "/videos" => "page#videos"
  
  get "page/haiti_one"
  match "/haiti_one" => "page#haiti_one"
  
  get "page/meal_packing"
  match "/meal_packing" => "page#meal_packing"

  get "page/mission_trips"
  match "/mission_trips" => "page#mission_trips"
    
  get "page/about_haiti"
  match "/about_haiti" => "page#about_haiti"
    
  get "page/orphan_care"
  match "/orphan_care" => "page#orphan_care"
  match "/orphan-care" => "page#orphan_care"
  
  get "page/education"
  match "/education" => "page#education"
  
  get "page/health_care"
  match "/health_care" => "page#health_care"
  
  get "page/three_cords"
  match "/three_cords" => "page#three_cords"
    
  get "page/meet_our_staff"
  match "/meet_our_staff" => "page#meet_our_staff"
  
  get "page/orphan_sponsorship"
  match "/orphan_sponsorship" => "page#orphan_sponsorship"
  
  get "page/clinic"
  match "/clinic" => "page#clinic"
  
  get "page/our_story"
  match "/our_story" => "page#our_story"
  
  get "page/community_health"
  match "/community_health" => "page#community_health"
 
  get "page/prosthetics"
  match "/prosthetics" => "page#prosthetics"
     
  get "page/internships"
  match "/internships" => "page#internships"
  
  get "/intern_application" => "interns#new"
  
  get "page/privacy"
  match "/privacy" => "page#privacy"
  
  get "page/financial_info"
  match "/financial_info" => "page#financial_info"
  
  get "page/press"
  match "/press" => "page#press"
  
  get "page/school_of_hope"
  match "/school_of_hope" => "page#school_of_hope"
  
  get "page/mwen_kapab"
  match "/mwen_kapab" => "page#mwen_kapab"
  
  get "page/vision_mission_resolution"
  match "/vision_mission_resolution" => "page#vision_mission_resolution"
  
  get "page/join_our_team"
  match "/join_our_team" => "page#join_our_team"
  
  get "page/partner_of_hope"
  match "/partner_of_hope" => "page#partner_of_hope"
  
  get "page/nutrition"
  match "/nutrition" => "page#nutrition"
  
  get "page/medical_mission_trips"
  match "/medical_mission_trips" => "page#medical_mission_trips"
     
  get "page/mission_trip_experinces"
  match "/mission_trip_experinces" => "page#mission_trip_experiences"
  
  get "page/mission_trip_experiences"
  match "/mission_trip_experiences" => "page#mission_trip_experiences"
  
  get "page/image_submit"
  match "/page/image_submit" => "page#image_submit"
   
  get "page/preparing_for_mission_trips"
  match "/preparing_for_mission_trips" => "page#preparing_for_mission_trips"
     
  get "page/request_info"
  match "/request_info" => "page#request_info"
  
  get "page/request_info_medical"
  match "/request_info_medical" => "page#request_info_medical"
     
  get "page/trip_costs"
  match "/trip_costs" => "page#trip_costs"
     
     
  get "page/trip_faqs"
  match "/trip_faqs" => "page#trip_faqs"
        
  get "page/communities_impacted"
  match "/communities_impacted" => "page#communities_impacted"
        
  get "page/church_partner"
  match "/church_partner" => "page#church_partner"
        
  get "page/vision_trip"
  match "/vision_trip" => "page#vision_trip"
    
  get "page/downloads"
  match "/downloads" => "page#downloads"
  
  get "page/faq"
  match "/faq" => "page#faq"
    
  get "page/make_donation"
  match "/make_donation" => "page#make_donation"
    
  get "page/be_a_partner"
  match "/be_a_partner" => "page#be_a_partner"
 
  get "page/volunteer"
  match "/volunteer" => "page#volunteer"   
    
  get "page/share_photos"
  match "/share_photos" => "page#share_photos"
    
  get "page/event"
  match "/event" => "page#event"
          
  get "page/sponsor_child"
  match "/sponsor_child" => "page#sponsor_child"
          
  get "page/learn_sponsor"
  match "/learn_sponsor" => "page#learn_sponsor"
          
  get "page/sponsor_faq"
  match "/sponsor_faq" => "page#sponsor_faq"
          
  get "page/gift_store"
  match "/gift_store" => "page#gift_store"
          
  get "page/write_my_child"
  match "/write_my_child" => "page#write_my_child"
  
  match "/write-my-child" => "page#write_my_child"
      
  get "page/console"
  match "/console" => "page#console"
  
  get "mymoh/account"
  get "mymoh/status_check"
  get "mymoh/home"
  get "mymoh/giving"
  get "mymoh/giving/edit" => "mymoh#givingedit"
  post "mymoh/giving/edit" => "mymoh#givingedit_post"
  get "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/giving/receipt/:gift_id" => "mymoh#givingreceipt"
  post "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/sponsorships"
  get "mymoh/mytrips"
  get "mymoh/login"
  get "mymoh/following"

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  def index
    @title = "Haiti Videos | Videos from Mission of Hope, Haiti"
    @meta = "Videos that provide a different view to MOH Haiti's earthquake relief, orphan care, education opportunities, and church advancement opportunities."
    @videos = Video.all
      respond_to do |format|
      format.html {render :layout=>"homeLayout"} # index.html.erb
      format.json { render json: @videos }
       @user = current_user
    @isadmin = is_admin_user?
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @user = current_user
    @isadmin = is_admin_user?
    @video = Video.find(params[:id])
    respond_to do |format|
      format.html {render :layout=>"homeLayout"} # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html {render :layout=>"homeLayout"} # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
    respond_to do |format|
       format.html {render :layout=>"homeLayout"}
    end
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(params[:video])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :ok }
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    Embed code<br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    Small embed code (size to 290 x 218)<br />
    <%= f.text_field :thumblink %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>
	<div id="content" style="padding-top: 50px;">
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>
</div>
</div>

app/views/videos/index.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>
	<div id="content" style="padding-top: 50px;">
		<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style alignRight">
<h4 style="float:left;">Share This: </h4>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>

</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-506b79724d720237"></script>
<!-- AddThis Button END -->
		<h1><span class="eyebrow">Mission of Hope Haiti </span>
		<br />
		Videos</h1>
		<% if !@user.nil? && @isadmin %>
		<h3 style="padding-bottom:25px;"><%= link_to 'Add a Video', new_video_path,:style=>"text-decoration:underline;" %></h3>
		<% end %>
		<div class="videoPostsWrapper">
			
			<!-- we are displaying some static videos here (the first four) -->
					<div class="video">
						<h4><a href="/videos/4">Mission of Hope Vision &amp; Mission</a></h4>
						<div class="videoPost">
							<iframe src="http://player.vimeo.com/video/30163926" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
						</div>
						<p>
							As an organization following Jesus Christ, Mission of Hope exists to bring life transformation to every man, woman, and child in Haiti. Hear our vision behind everything we do at Mission of Hope. <a href="/videos/4">Read More &raquo;</a>
						</p>
					</div>	
					
					<div class="video">
						<h4><a href="/videos/2">Advancing The Church in Haiti</a></h4>
						<div class="videoPost">
							<iframe src="http://player.vimeo.com/video/48615727" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
						</div>
						<p>
							Church advancement is the Church of North America partnering with Mission of Hope, Haiti to serve the Church in Haiti. Singularly, or along with other churches. Your church will have the... <a href="/videos/2">Read More &raquo;</a>
						</p>
					</div>
					<div class="video">
						<h4><a href="/videos/1">Mission of Hope Ministry Overview</a></h4>
						<div class="videoPost">
							<iframe src="http://player.vimeo.com/video/31550572" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
						</div>
						<p>
							As an organization grounded in the gospel of Jesus Christ, we seek to daily serve the people of Haiti and bring hope to the hopeless. We are there to meet the physical and spiritual needs of the... <a href="/videos/1">Read More &raquo;</a>
						</p>
					</div>
					<div class="video">
						<h4><a href="/videos/3">Mwen Kapab</a></h4>
						<div class="videoPost">
							<iframe src="http://player.vimeo.com/video/45280018" width="400" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
						</div>
						<p>
							Mwen Kapab. Translation: “I can.”
							This is the message MOH is empowering the students of Haiti with as we continue the development of our educational curriculum.
							Meet the visionary behind our... <a href="/videos/3">Read More &raquo;</a>
						</p>
					</div>
					
			<!-- end static -->
			
			<% @videos.each do |video| %>
				<% if video.id > 4 %>
					<div class="video">
						<h4><a href="/videos/<%= video.id %>"><%= video.title %></a></h4>
						<div class="videoPost">
							<%= video.link.html_safe %>
						</div>
						<p>
							<%= truncate(video.description,:length=>200,:separator=>' ') %> <a href="/videos/<%= video.id %>">Read More &raquo;</a>
						</p>
						<% if !@user.nil? && @user.is_admin?%>
						<p class="editPostsLink">
							<%= link_to 'Edit', edit_video_path(video) %> |
							<%= link_to 'Back', videos_path %>
						</p>
						<% end %>
					</div>
				<% end %>
			<% end %>

			<div class="clearfix">
				&nbsp;
			</div>
		</div>

		<% if !@user.nil? && @isadmin %>
		<h4><%= link_to 'New Video', new_video_path %></h4>
		<% end %>
	
	</div>
</div>
<div class="clear">&nbsp;</div>

app/views/videos/new.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>
	<div id="content" style="padding-top: 50px;">
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>
</div>
</div>

app/views/videos/show.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>
	<div id="content" style="padding-top: 50px;">
		<p id="notice">
			<%= notice %>
		</p>
		<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style alignRight">
<h4 style="float:left;">Share This: </h4>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>

</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-506b79724d720237"></script>
<!-- AddThis Button END -->
		<h1><span class="eyebrow">Mission of Hope Haiti </span>
		<br />
		Videos</h1>
		<div class="videoPostsWrapper">
		<div class="videoSingle">
			<h4><%= @video.title %></h4>
			<div class="videoPostSingle">
				<%= @video.link.html_safe %>
			</div>
			</div>
			<div class="videoDescription">
<p>
				<%= @video.description %>
			</p>
			<% if !@user.nil? && @user.is_admin?%>
			<p class="editPostsLink">
				<%= link_to 'Edit', edit_video_path(@video) %> |
				<%= link_to 'Back', videos_path %>
			</p>
			<% end %>
		
<div class="clearfix">
				&nbsp;
			</div>
			</div>
	</div>
</div>