config/routes.rb
Mohhaiti::Application.routes.draw do

  match "/donate-today" => redirect("https://secure3.convio.net/mohh/site/Donation2?df_id=1600&1600.donation=form1"), :as => :donate_today 

  get "/intern_thank_you" => "page#intern_thank_you"
  
  resources :interns do

    member do
      get "archive"
      put "archive"
      post "archive"
    end
    match "/interns/:id/archive" => "interns#archive"
    
  end  
  
  get "/archived_interns" => "page#archived_interns"

  resources :subscriptions

  match "/blog/feed.xml" => "posts#rss", :action => 'rss'
  
  match "/bluetoblock" => "projects#bluetoblock"
  put "/projects/5" => "projects#update", :id => 5
  match "/projects/5" => "projects#bluetoblock"

  get "projects/transition_home" => "projects#project15extra"
  get "projects/project15extra" =>  "projects#project15extra"
  resources :news

  resources :videos

  resources :events

  resources :categories

  get "category/index"

  get "category/show"

  get "category/update"

  resources :posts

  resources :experiences

  resources :partners

  root :to => 'home#index'

  resources :contents

  resources :tags

  resources :updates

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  

  match "/users/password_reset" => "users#password_reset"
  match "/users/password_reset/:token" => "users#password_reset_edit"
  resources :users

  resources :projects

  resources :communities
  
  resources :sessions
  
  resources :blog, :controller => "posts"
  
  resources :villages, :controller => "communities"
  
  get "home/index"
  
  

  match "/about_moh" => redirect("/about_us")
  match "/about_moh/history" => redirect("/")
  match "/about_moh/in_the_news/" => redirect("/press")  
  match "/about_moh/staff/:any" => redirect("/meet_our_staff")
  match "/about_moh/staff/" => redirect("/meet_our_staff")
  match "/about_moh/vision_and_resolution/" => redirect("/vision_mission_resolution")
  match "/about_moh/our_progress_in_haiti/" => redirect("/what-we-do")
  match "/about_moh/haiti_info/" => redirect("/about_haiti")
  match "/about_moh/contact_us/" => redirect("/contact_us")
  match "/about_moh/privacy_policy/" => redirect("/privacy")
  match "/about_moh/videos/" => redirect("/videos")
  match "/about_moh/what_we_believe" => redirect("/")
  
  match "/blog" => redirect("/posts")
  
  match "/contact-us" => redirect("/contact_us")
  
  match "/get_involved/" => redirect("/take-action")
  match "/get_involved/donations" => redirect("/take-action")
  match "/get_involved/partners_of_hope" => redirect("/partner_of_hope")
  match "/get_involved/child_sponsorships/faq/" => redirect("/sponsor_faq")
  match "/get_involved/child_sponsorships/cs_store/" => redirect("/gift_store")
  match "/get_involved/child_sponsorships/" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/orphan_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/child_sponsorships/student_sponsorship" => redirect("/child-sponsorship")
  match "/get_involved/church_partnerships" => redirect("/church_partner")
  match "/get_involved/church_partnerships/vision_trip_dates" => redirect("/vision_trip")
  match "/get_involved/employment_opportunities/" => redirect("/about_us")
  match "/get_involved/events/" => redirect("/events")
  match "/get_involved/internships/" => redirect("/internships")
  match "/get_involved/mission_trips/" => redirect("/mission_trips")
  match "/get_involved/mission_trips/faq1" => redirect("/trip_faqs")
  match "/get_involved/mission_trips/preparing_for_your_trip/" => redirect("/preparing_for_mission_trips")
  match "/get_involved/mission_trips/trip_costs" => redirect("/trip_costs")
  match "/get_involved/mission_trips/trip_dates" => redirect("/trip_dates")
  match "/get_involved/prayer_needs/" => redirect("/take-action")
  
  match "/news" => redirect("/press")
  
  get "/sponsorship/say_yes" => "sponsorship#say_yes"
  match "/take-the-plunge" => redirect("/mission_trips")
  
  match "/what_we_do/3cords/" => redirect("/three_cords")
  match "/what_we_do/church_advancement/" => redirect("/church_advancement")
  match "/what_we_do/education1/" => redirect("/education")
  match "/what_we_do/education1/christian_curriculum/" => redirect("/mwen_kapab")
  match "/what_we_do/future_plans/" => redirect("/projects")
  match "/what_we_do/future_plans/:any" => redirect("/projects")
  match "/what_we_do/haiti_one/" => redirect("/haiti_one")
  match "/what_we_do/medical_care/" => redirect("/health_care")
  match "/what_we_do/medical_care/prosthetics_lab" => redirect("/prosthetics")
  match "/what_we_do/medical_care/community_health_program" => redirect("/community_health")
 
  match "/what_we_do/moh_500/" => redirect("/projects/5")
  match "/what_we_do/nutrition/" => redirect("/nutrition")
  match "/what_we_do/orphan_care/" => redirect("/orphan_care")
  match "/what_we_do/" => redirect("/what-we-do")
  
  
  
  
  get "page/newsletter_thank_you"
  match "/newsletter_thank_you" => "page#newsletter_thank_you"
  
  get "page/sitemap"
  match "/sitemap" => "page#sitemap"
  
  get "page/what_we_do"
  match "/what-we-do" => "page#what_we_do"
  
  get "page/about_us"
  match "/about_us" => "page#about_us"
  
  get "page/caprojects"
  match "/caprojects" => "page#caprojects"
  
  get "page/contact_us"
  match "/contact_us" => "page#contact_us"
  
  get "page/videos"
  match "/videos" => "page#videos"
  
  get "page/haiti_one"
  match "/haiti_one" => "page#haiti_one"
  
  get "page/meal_packing"
  match "/meal_packing" => "page#meal_packing"

  get "page/mission_trips"
  match "/mission_trips" => "page#mission_trips"
    
  get "page/about_haiti"
  match "/about_haiti" => "page#about_haiti"
    
  get "page/orphan_care"
  match "/orphan_care" => "page#orphan_care"
  match "/orphan-care" => "page#orphan_care"
  
  get "page/education"
  match "/education" => "page#education"
  
  get "page/health_care"
  match "/health_care" => "page#health_care"
  
  get "page/three_cords"
  match "/three_cords" => "page#three_cords"
    
  get "page/meet_our_staff"
  match "/meet_our_staff" => "page#meet_our_staff"
  
  get "page/orphan_sponsorship"
  match "/orphan_sponsorship" => "page#orphan_sponsorship"
  
  get "page/clinic"
  match "/clinic" => "page#clinic"
  
  get "page/our_story"
  match "/our_story" => "page#our_story"
  
  get "page/community_health"
  match "/community_health" => "page#community_health"
 
  get "page/prosthetics"
  match "/prosthetics" => "page#prosthetics"
     
  get "page/internships"
  match "/internships" => "page#internships"
  
  get "/intern_application" => "interns#new"
  
  get "page/privacy"
  match "/privacy" => "page#privacy"
  
  get "page/financial_info"
  match "/financial_info" => "page#financial_info"
  
  get "page/press"
  match "/press" => "page#press"
  
  get "page/school_of_hope"
  match "/school_of_hope" => "page#school_of_hope"
  
  get "page/mwen_kapab"
  match "/mwen_kapab" => "page#mwen_kapab"
  
  get "page/vision_mission_resolution"
  match "/vision_mission_resolution" => "page#vision_mission_resolution"
  
  get "page/join_our_team"
  match "/join_our_team" => "page#join_our_team"
  
  get "page/partner_of_hope"
  match "/partner_of_hope" => "page#partner_of_hope"
  
  get "page/nutrition"
  match "/nutrition" => "page#nutrition"
  
  get "page/medical_mission_trips"
  match "/medical_mission_trips" => "page#medical_mission_trips"
     
  get "page/mission_trip_experinces"
  match "/mission_trip_experinces" => "page#mission_trip_experiences"
  
  get "page/mission_trip_experiences"
  match "/mission_trip_experiences" => "page#mission_trip_experiences"
  
  get "page/image_submit"
  match "/page/image_submit" => "page#image_submit"
   
  get "page/preparing_for_mission_trips"
  match "/preparing_for_mission_trips" => "page#preparing_for_mission_trips"
     
  get "page/request_info"
  match "/request_info" => "page#request_info"
  
  get "page/request_info_medical"
  match "/request_info_medical" => "page#request_info_medical"
     
  get "page/trip_costs"
  match "/trip_costs" => "page#trip_costs"
     
     
  get "page/trip_faqs"
  match "/trip_faqs" => "page#trip_faqs"
        
  get "page/communities_impacted"
  match "/communities_impacted" => "page#communities_impacted"
        
  get "page/church_partner"
  match "/church_partner" => "page#church_partner"
        
  get "page/vision_trip"
  match "/vision_trip" => "page#vision_trip"
    
  get "page/downloads"
  match "/downloads" => "page#downloads"
  
  get "page/faq"
  match "/faq" => "page#faq"
    
  get "page/make_donation"
  match "/make_donation" => "page#make_donation"
    
  get "page/be_a_partner"
  match "/be_a_partner" => "page#be_a_partner"
 
  get "page/volunteer"
  match "/volunteer" => "page#volunteer"   
    
  get "page/share_photos"
  match "/share_photos" => "page#share_photos"
    
  get "page/event"
  match "/event" => "page#event"
          
  get "page/sponsor_child"
  match "/sponsor_child" => "page#sponsor_child"
          
  get "page/learn_sponsor"
  match "/learn_sponsor" => "page#learn_sponsor"
          
  get "page/sponsor_faq"
  match "/sponsor_faq" => "page#sponsor_faq"
          
  get "page/gift_store"
  match "/gift_store" => "page#gift_store"
          
  get "page/write_my_child"
  match "/write_my_child" => "page#write_my_child"
  
  match "/write-my-child" => "page#write_my_child"
      
  get "page/console"
  match "/console" => "page#console"
  
  get "mymoh/account"
  get "mymoh/status_check"
  get "mymoh/home"
  get "mymoh/giving"
  get "mymoh/giving/edit" => "mymoh#givingedit"
  post "mymoh/giving/edit" => "mymoh#givingedit_post"
  get "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/giving/receipt/:gift_id" => "mymoh#givingreceipt"
  post "mymoh/giving/history" => "mymoh#givinghistory"
  get "mymoh/sponsorships"
  get "mymoh/mytrips"
  get "mymoh/login"
  get "mymoh/following"

app/models/update.rb
class Update < ActiveRecord::Base

  has_many :assets
  has_and_belongs_to_many :categories
  has_and_belongs_to_many :communities
  has_and_belongs_to_many :projects
  has_and_belongs_to_many :tags
  belongs_to :user
  

  accepts_nested_attributes_for :assets, :allow_destroy => true


end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  # GET /updates
  # GET /updates.json
  def index
    #@updates = Update.all.reverse
    @title = "Haiti Updates | Updates on What's Happening at Mission of Hope, Haiti"
    @meta ="Get updates on what's happening in Haiti from Mission of Hope, Haiti (MOH)."
    @cid = params[:cid]
    @user = current_user
    @isadmin = is_admin_user?
    @itemCount = 0
    if @cid.nil?
      #@jason = Update.all.to_gmaps4rails
      @categories = Category.joins(:updates).order("categoryname asc").uniq
      @updates = Update.order("postdate desc").limit(40)
    else
      @updates = Update.joins(:categories).where("category_id=" + @cid).order("postdate desc").limit(40)
      #@jason = @updates.to_gmaps4rails
      @category = Category.find(@cid)
    end

    respond_to do |format|
      format.html {render :layout=>"homeLayout"}# index.html.erb
      format.json { render json: @updates }
    end
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = Update.find(params[:id])
    @photo = @update.assets.last
    @blogs = Post.last(3)
    unless @update.categories.count == 0
      @cat=@update.categories.order("categoryname asc").limit(1)
      @cat2=@update.categories.order("categoryname asc").offset(1)
      @cats = @update.categories
      
      @related_result = []
      @cats.each do |cat|
        @related_result += Update.joins(:categories).where("category_id=" + cat.id.to_s).reverse
        @related_result = @related_result.uniq{|x| x.title}
      end
      
      @blogs = []
      @cats.each do |cat|
        @blogs += Post.joins(:categories).where("category_id=" + cat.id.to_s)
        @blogs = @blogs.uniq{|x| x.title}
      end
      
      @related_projects = []
      @cats.each do |cat|
        @related_projects += Project.joins(:categories).where("category_id=" + cat.id.to_s).reverse
        @related_projects = @related_projects.uniq{|x| x.projectname}
      end
      
    end
    @isadmin = is_admin_user?

    respond_to do |format|
      format.html {render :layout=>"homeLayout"} # show.html.erb
      format.json { render json: @update }
    end
  end

  # GET /updates/new
  # GET /updates/new.json
  def new
    if is_admin_user?
      @update = Update.new
      @update.assets.build

      respond_to do |format|
        format.html {render :layout=>"homeLayout"} # new.html.erb
        format.json { render json: @update }
      end
    else
      respond_to do |format|
        format.html { redirect_to "/updates/" }
      end
    end
  end

  # GET /updates/1/edit
  def edit
    if is_admin_user?
      @update = Update.find(params[:id])
      @update.assets.build
      respond_to do |format|
         format.html {render :layout=>"homeLayout"}
      end
    else
      respond_to do |format|
        format.html { redirect_to "/updates/" }
      end
    end
  end

  # POST /updates
  # POST /updates.json
  def create
    puts "Title: " + params[:update]["title"]
    @update = Update.new(params[:update])
    
    unless params[:update]["title"].empty? or params[:update]["body"].empty?

      respond_to do |format|
        if @update.save
          format.html { redirect_to @update, notice: 'Update was successfully created.' }
          format.json { render json: @update, status: :created, location: @update }
          
        else
          format.html { render action: "new" }
          format.json { render json: @update.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /updates/1
  # PUT /updates/1.json
  def update
    @update = Update.find(params[:id])

    respond_to do |format|
      if @update.update_attributes(params[:update])
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update = Update.find(params[:id])
    @update.destroy

    respond_to do |format|
      format.html { redirect_to updates_url }
      format.json { head :ok }
    end
  end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= form_for(@update) do |f| %>
  <% if @update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% @update.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Title (Required)<br />
    <%= f.text_field :title, :required=>true %>
  </div>
  <div class="field author">
    Author <br />
    <%= f.text_field :author%>
  </div>
  <div class="field postdate">
    Post Date <br />
    <%= date_select :update, :postdate %>
  </div>
  <div class="clearfix"></div>
  <div class="field">
   Body<br />
    <%= f.text_field :body %>
  </div>
  <div class="collectionSelector thirdcat">
  	Select Category: <br /><%= collection_select 'update', 'category_ids', Category.order("categoryname asc"), :id, :categoryname, { :include_blank => 'None'}, { :multiple => true, :categoryname =>'update[category_ids][]',:selected => 0 } %>
  </div>
  <div class="collectionSelector thirdcat">
  	Select Related Projects: <br /><%= collection_select 'update', 'project_ids', Project.order("projectname asc"), :id, :projectname, { :include_blank => 'None'}, { :multiple => true, :projectname =>'update[project_ids][]',:selected => 0 } %>
  </div>
  
  <div class="collectionSelector thirdcat">
  	Select Related Villages: <br /><%= collection_select 'update', 'community_ids', Community.order("communityname asc"), :id, :communityname, { :include_blank => 'None'}, { :multiple => true, :communityname =>'update[community_ids][]',:selected => 0 } %>
  </div>
  <div class="clearfix"></div>
  <div class="field">
    Media<br />
    <%= f.text_field :media %>
  </div>
  <div style="margin-top:15px;"><strong>Add image(s):</strong>
  <%= f.fields_for :assets do |asset_fields| %>
  	<% if asset_fields.object.new_record? %>
  		<p>
  			<%= asset_fields.file_field :asset%>
  		</p>
  	<% end%>
  <% end %>
  <%= f.fields_for :assets do |asset_fields| %>
  	<% unless asset_fields.object.new_record? %>
  		<p>
  			<%= link_to image_tag(asset_fields.object.asset.url(:thumb)),asset_fields.object.asset.url(:large)%>
  			<%= asset_fields.check_box :_destroy %> Remove Image
  		</p>
  	<% end %>
  <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>

	<div id="content" style="padding-top:50px;">
<h1>Editing update</h1>

<%= render 'form' %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>
</div>
</div>

app/views/updates/index.html.erb
<div id="wrapper">
	<%=render 'layouts/navBar'%>
<div id="content" style="padding-top: 40px;">
<% if @cid.nil?%>
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style alignRight">
<h4 style="float:left;">Share This: </h4>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>

</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-506b79724d720237"></script>
<!-- AddThis Button END -->
<h1><span class="eyebrow">Mission of Hope Haiti</span><br />Updates</h1>
<% else %>
	<h1><%=@category.categoryname %> Updates</h1>
<% end %>

<div style="width:990px; height:100%;">
	<div id="container" class="transitions-enabled clearfix" style="clear:both;">
		<% @updates.each do |update| %>
			<% @photo = update.assets.last%>
				<div class="item">
					<% unless @photo.nil? %>
			  			<%= image_tag @photo.asset.url(:medium),:title=>update.body,:alt=>update.body  %>
			  		<%end%>
					<h4><a href="/updates/<%=update.id%>"><%= update.title %></a></h4>
					<p><%= update.postdate.strftime("%b %e, %Y") %></p>
			  		
			  		<% unless update.author.blank? or update.author.nil? %>
			  			<p><span class="update">Update from <%= update.author%>:</span></p>
			  		<% end %>
		  			<p><%= update.body %></p>
		  		</div>
		<% end %>
	</div>
</div>
<script src="/assets/javascript/jquery.masonry.min.js"></script>
<script>
	var $container = $('#container');
	$container.imagesLoaded(function(){
  		$container.masonry({
  			itemSelector: '.item',
  			//columnWidth: 1,
  			isAnimated: true,
  			animationOptions: {
    			duration: 500,
    			easing: 'linear',
    			queue: false
  			}
  		});
	});
</script>


<br />
<%if @isadmin%>
<%= link_to 'New Update', new_update_path %>
<%end%>
</div>

app/views/updates/new.html.erb
<div id="wrapper">
	<%= render 'layouts/navBar'%>

	<div id="content" style="padding-top:50px;">
<h1>New update</h1>

<%= render 'form' %>

<%= link_to 'Back', updates_path %>
</div>
</div>

app/views/updates/show.html.erb
<% @title = @update.title + " | Mission of Hope Haiti"%>
<div id="wrapper">
	<%=render 'layouts/navBar'%>
<div id="content" style="padding-top: 20px;">
	<div class="clearfix"></div>
<p id="notice"><%= notice %></p>
<div id="contentLeft560">
<div class="updateDate" style="margin-top:30px;">
				<span class="month"><%= @update.postdate.strftime("%b")%></span>
				<br />
				<span class="date"><%= @update.postdate.strftime("%d")%></span>
				<br />
				<span class="year"><%= @update.postdate.strftime("%Y")%></span>
			</div>
		<h2>
			<span class="eyebrow">Mission of Hope Haiti Updates</span>
			<br />
			<%= @update.title %>
		</h2>
		<p class="meta" >
    		<%unless @update.author.nil? || @update.author.blank?%>
			<p>Update from <%=@update.author%></p>
			<%end%>
    		<% unless @update.categories.count == 0%>
			Related to:
		<a href="/updates/?cid=<%=@cat.first.id%>"><%= @cat.first.categoryname %></a>
		<% unless @cat2.nil? %>
			<% @cat2.each do |cat2|%>
			, <a href="/updates/?cid=<%=cat2.id%>"><%= cat2.categoryname%></a>
			<% end%>
		<%end%>
<% end %>
    	</p>
    	<div class="clearfix"></div>
<%unless @photo.nil?%>
<p><img src="<%=@photo.asset.url(:large)%>" class="updatesBorder" /></p>
<%end%>
<p>
  <%= @update.body %>
</p>

<% if !@update.media.nil? %>
<p>
  <%= @update.media.html_safe %>
</p>
<% end %>

<%if @isadmin%>
<%= link_to 'Edit', edit_update_path(@update) %> | <%= link_to 'Destroy', @update, confirm: 'Are you sure?', method: :delete %> | <%= link_to 'Back', updates_path %>
<%end%>


<% if @related_result %>
	<% if @related_result.length > 1 %>
	<div class="update560"></div>
		<h3>Other <%= @cat.first.categoryname %><%if !@cat2.nil? %><% @cat2.each do |cat2| %>, <%= cat2.categoryname %><%end%><%end%> updates: </h3>
		<!--<h3 class="update560" style="font-size: 1em;">-->
			<% @related_result.each do |related|%>
				<%if related.id != @update.id %>
					<div class="update560" style="line-height: 1.3em; height=120px;">
						<h4 style="padding-bottom: 5px;"><a href="/updates/<%=related.id%>"><%=related.title%></a><br/></h4>
						<% unless related.assets.last.nil? %>
							<img src="<%=related.assets.last.asset.url(:thumb)%>" style="float:left; padding-right: 15px; padding-bottom: 5px;" />
						<%end %>
						<%= related.body %>
					<div class="clearfix"><!--x--></div>
					</div>
				<%end%>
			<% end%>
		<!--</h3>-->
	<% end %>
<%end%>

</div>


<div id="contentRight300"> 
	<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style addthis_32x32_style" style="margin-top:40px;">
<h4 style="float:left;">Share This: </h4>
<a class="addthis_button_preferred_1"></a>
<a class="addthis_button_preferred_2"></a>
<a class="addthis_button_preferred_3"></a>
<a class="addthis_button_preferred_4"></a>

</div>
<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
<script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-506b79724d720237"></script>
<!-- AddThis Button END -->
	<% if @blogs.count != 0 %>
		<div class="updatesWrapper" style="margin-top:20px;">
			<h3>MOH in Action</h3>
			<div class="speechBubble" style="position: absolute; top: -71px; right: 39px;"><p>latest blogs</p></div>
			<%@blogs.each do |blog|%>
				<div class="update300">
				<p class="meta">	<% 
						created = blog.postdate 
					%>
					<% if created %>
						<%= created.strftime("%b")%> <%=created.strftime("%d")%>, <%=created.strftime("%Y")%>
					<% end %>
				</p>
				<div class="updatePost300">
					<h3><a href="/blog/<%=blog.id%>"><%=blog.title%></a></h3>
					<% if !blog.thumb_id.nil? %>
						<% @thumbimg = Asset.find(blog.thumb_id) %>
						<% if @thumbimg.nil? %>
						  <% @thumbimg = blog.assets.first %>
						<% end %>
					<% else %>
					  <% if !blog.assets.nil? %>
						  <% @thumbimg = blog.assets.first %>
					  <% end %>
					<% end %>
					<p>
						<% if !@thumbimg.nil? %>
							<img src="<%=@thumbimg.asset.url(:thumb)%>" style="float:left; padding-right: 15px; padding-bottom: 5px;" />
						<% end %>
						<%=truncate(strip_tags(blog.body),:length=>110,:separator=>' ') %> <a href="/blog/<%=blog.id%>">Read Story &raquo;</a>
					</p>
					<div class="clearfix"><!--x---></div>
					<% @cat = blog.categories.order("categoryname asc").limit(1)%>
					<p class="meta">
						<%unless @cat.count==0%>Related Category: <a href="/blog/?cid=<%=@cat.first.id%>"><%=@cat.first.categoryname%></a><%end%> <%if !blog.author.nil? && !blog.author.blank?%><%unless @cat.count==0%>| <%end%>Update from: <%=blog.author%><%end%>
					</p>
					
				</div>
				<div class="clearfix"></div>
				</div>
			<%end%>
			<div class="updateNav"><a href="/updates">Read all updates from Mission of Hope &raquo;</a></div>
		</div>
	<% end %>

	
	

<% if @related_projects %>
<% if @related_projects.length > 0 %>
	<h3 style="width:295px;" class="projectDetailButton"><strong>Related Projects: </strong>
	<% @related_projects.each do |related|%>
		<a href="/projects/<%=related.id%>"><%=related.projectname%></a><br>
	<% end%>
	</h3>
<% end %>
<% end%>

<div class="clearfix"></div>
</div>

<div class="clearfix" style="height:40px;"><!--x--></div>

</div></div>